name: Deploy Wasm App to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 21

            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '20'

            -   name: Make Gradle Wrapper Executable
                run: chmod +x ./gradlew

            -   name: Build Wasm App
                run: ./gradlew :wasm-app:wasmJsBrowserDistribution

            -   name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: .build/WasmAppDistribution
                    keep_files: true
